version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: cafepos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cafepos
    ports:
      - "5433:5432"
    volumes:
      - cafepos_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cafepos-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - cafepos_redisdata:/data
    restart: unless-stopped

volumes:
  cafepos_pgdata:
  cafepos_redisdata:
